In [1]:

from google.colab import files

uploaded = files.upload()

Saving Day11_Messy_Company_Employee_Dataset.csv to Day11_Messy_Company_Employee_Dataset.csv

In [3]:
import pandas as pd

In [4]:

df = pd.read_csv("Day11_Messy_Company_Employee_Dataset.csv")

### Inspect the dataset

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.sample(5)

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.dtypes

In [ ]:
df.info()

### check missing values

In [ ]:
df.isnull().sum()

In [ ]:
(df.isnull().sum() / len(df)) * 100

In [6]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage

Employee_ID          0.000000
Employee_Name        0.000000
Department           3.184713
Job_Title            0.000000
Age                  2.547771
Gender               3.184713
Annual_Salary        3.184713
Experience_Years     1.910828
Joining_Date         0.000000
City                 3.184713
Performance_Score    1.910828
Work_Mode            1.273885
dtype: float64

Check Duplicates

In [7]:
df.duplicated().sum()

np.int64(7)

In [8]:
df[df.duplicated()]

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
55,EMP0097,Zoya Shah,Finance,Financial Analyst,41.0,Male,81531.0,4.1,2023-06-05,Mumbai,4.0,Office
61,EMP0075,Manya Joshi,Sales,Sales Manager,29.0,Male,92623.0,11.9,2025-08-17,Jaipur,4.0,Hybrid
100,EMP0139,Simran Sharma,Finance,Accountant,32.0,Female,110617.0,10.3,2021-08-03,Mumbai,3.0,Office
104,EMP0021,Riya Khan,Operations,Operations Executive,49.0,Female,71549.0,4.6,2024-09-20,Chandigarh,3.0,Hybrid
110,EMP0048,Nikhil Dar,Finance,Financial Analyst,27.0,Female,NaN,10.1,2020-06-18,Chandigarh,2.0,Office
139,EMP0150,Nikhil Khan,Finance,Finance Manager,43.0,Male,129905.0,16.3,2018-04-10,Chennai,3.0,Remote
156,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote

### Handle missing values

In [9]:
df = df.dropna()

In [ ]:
df.dropna(thresh=5)

### **Mean Median Mode imputation**

In [14]:
df["Age"].mean()

np.float64(37.936)

In [11]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [12]:
df["Annual_Salary"] = df["Annual_Salary"].fillna(df["Annual_Salary"].median())

In [13]:
df["Department"] = df["Department"].fillna(df["Department"].mode()[0])

Forwar and back fill

In [15]:
df["Department"] = df["Department"].ffill()

Remove duplicates

In [16]:
df.duplicated().sum()

np.int64(6)

In [17]:
df = df.drop_duplicates()

In [18]:
df.duplicated().sum()

np.int64(0)

Checking missing values

In [19]:
df.isnull().sum()

Employee_ID          0
Employee_Name        0
Department           0
Job_Title            0
Age                  0
Gender               0
Annual_Salary        0
Experience_Years     0
Joining_Date         0
City                 0
Performance_Score    0
Work_Mode            0
dtype: int64

Checking the cleaned dataset

In [20]:
df.head()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid
5,EMP0117,Zoya Kapoor,Finance,Finance Manager,42.0,Male,128567.0,15.4,2017-08-02,Chennai,4.0,Hybrid
6,EMP0081,Maryam Mir,Marketing,Content Strategist,37.0,Male,58878.0,1.8,2024-01-18,Pune,2.0,Office

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 119 entries, 1 to 154
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        119 non-null    object
 1   Employee_Name      119 non-null    object
 2   Department         119 non-null    object
 3   Job_Title          119 non-null    object
 4   Age                119 non-null    float64
 5   Gender             119 non-null    object
 6   Annual_Salary      119 non-null    float64
 7   Experience_Years   119 non-null    float64
 8   Joining_Date       119 non-null    object
 9   City               119 non-null    object
 10  Performance_Score  119 non-null    float64
 11  Work_Mode          119 non-null    object
dtypes: float64(4), object(8)
memory usage: 16.2+ KB

In [22]:
df.shape

(119, 12)

In [23]:
df.dtypes

Employee_ID           object
Employee_Name         object
Department            object
Job_Title             object
Age                  float64
Gender                object
Annual_Salary        float64
Experience_Years     float64
Joining_Date          object
City                  object
Performance_Score    float64
Work_Mode             object
dtype: object

In [24]:
df.duplicated().sum()

np.int64(0)