Student Dataset Summary Report

In [1]:
from google.colab import files

uploaded = files.upload()

Saving Day7_Student_Dataset.csv to Day7_Student_Dataset.csv

In [7]:
import pandas as pd

df = pd.read_csv("Day7_Student_Dataset.csv")
df.head()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

In [8]:
df.tail()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

random sample

In [ ]:
df.sample(5)

Dataset Shape

In [9]:
df.shape

(25, 7)

Dataset Columns

In [10]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='object')

Dataset Index

In [ ]:
df.index

Data Types

In [ ]:
df.dtypes

Dataset Information

In [ ]:
df.info()

Descriptive Statistics

In [11]:
df.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

Missing Values

In [ ]:
df.isnull().sum()

### Conclusion
The dataset was successfully loaded and explored using Pandas.
The analysis provided information about its structure, columns,
data types, descriptive statistics, and missing values.